version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo apt update -y
      - sudo apt install apache2 -y
      - sudo apt install -y git unzip awscli

  pre_build:
    commands:
      - echo "Cloning latest code from GitHub..."
      - rm -rf /var/www/html/*
      - git clone -b main https://github.com/vishrut-golakiya/html-demo.git /var/www/html/
      - sudo chown -R www-data:www-data /var/www/html/
      - sudo chmod -R 755 /var/www/html/

  build:
    commands:
      - echo "Restarting apche"

  post_build:
    commands:
      - echo "Deployment Completed Successfully!"
  
artifacts:
  files:
    - '**/*'
  base-directory: /var/www/html
